# Generated by Django 5.2 on 2025-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_formgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
